.TH "demos/demo.c" 3 "Version 0.0.1" "VCS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
demos/demo.c
.SH SYNOPSIS
.br
.PP
\fR#include <ctype\&.h>\fP
.br
\fR#include <math\&.h>\fP
.br
\fR#include 'VCS/VCS\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint32_t \fBblinkblueshader\fP (int x, int y, void *arg)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint32_t blinkblueshader (int x, int y, void * arg)"

.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for VCS from the source code\&.
