.TH "md__r_e_a_d_m_e" 3 "Version 0.0.1" "VCS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- cmwade-vcs 
.PP


.PP
Charlotte's solo project for 324

.PP
VCS (short for Visual Character System) is an sdl-based graphics system designed to provide the basic functionality of ncurses, plus some extras\&. It is designed to merge the simplicity and ease-of-use of ascii-art graphics with the capabilities of modern graphics and audio systems\&.
.SS "Features"
.IP "\(bu" 2
SDL window which renders an array of 8x8 ASCII characters in its own thread, in a style much like ncurses\&.
.IP "\(bu" 2
Character foreground and background colors configurable by RGB; no more memorizing color codes
.IP "\(bu" 2
Keyboard reading handled through SDL
.IP "\(bu" 2
Basic support for playing one-off audio sounds as well as looping a track
.IP "\(bu" 2
(stretch goal) Shaders allow you to overlay effects on the background and foreground color layers, rendered on a 1/8 character size grid 
.PP

