.TH "src/VCS_dynchar.c" 3 "Version 0.0.1" "VCS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/VCS_dynchar.c
.SH SYNOPSIS
.br
.PP
\fR#include 'VCS_dynchar\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBVCS_dynchar_t\fP \fBVCS_make_dynchar\fP (char c, \fBVCS_cpushader\fP fg, \fBVCS_cpushader\fP bg, void *fgarg, void *bgarg)"
.br
.ti -1c
.RI "uint32_t \fBVCS_blackshader\fP (int x, int y, void *arg)"
.br
.ti -1c
.RI "uint32_t \fBVCS_whiteshader\fP (int x, int y, void *arg)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint32_t VCS_blackshader (int x, int y, void * arg)"

.SS "\fBVCS_dynchar_t\fP VCS_make_dynchar (char c, \fBVCS_cpushader\fP fg, \fBVCS_cpushader\fP bg, void * fgarg, void * bgarg)"

.SS "uint32_t VCS_whiteshader (int x, int y, void * arg)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VCS from the source code\&.
