.TH "include/VCS_info.h" 3 "Version 0.0.1" "VCS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/VCS_info.h
.SH SYNOPSIS
.br
.PP
\fR#include 'SDL3/SDL\&.h'\fP
.br
\fR#include 'SDL3/SDL_main\&.h'\fP
.br
\fR#include 'SDL3_ttf/SDL_ttf\&.h'\fP
.br
\fR#include 'VCS_renderpanel\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBVCS_info\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBVCS_info\fP \fBVCS_info_t\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBVCS_info\fP \fBVCS_info_t\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VCS from the source code\&.
