.TH "src/VCS_renderpanel.c" 3 "Version 0.0.1" "VCS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/VCS_renderpanel.c
.SH SYNOPSIS
.br
.PP
\fR#include <stdlib\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br
\fR#include 'VCS_dynchar\&.h'\fP
.br
\fR#include 'VCS_renderpanel\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBVCS_rp_drawto\fP (\fBVCS_renderpanel_t\fP *source, \fBVCS_renderpanel_t\fP *dest, int x, int y, int transparent)"
.br
.ti -1c
.RI "void \fBVCS_rp_clear\fP (\fBVCS_renderpanel_t\fP *rp)"
.br
.ti -1c
.RI "void \fBVCS_rp_free_contents\fP (\fBVCS_renderpanel_t\fP *rp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void VCS_rp_clear (\fBVCS_renderpanel_t\fP * rp)"

.SS "void VCS_rp_drawto (\fBVCS_renderpanel_t\fP * source, \fBVCS_renderpanel_t\fP * dest, int x, int y, int transparent)"

.SS "void VCS_rp_free_contents (\fBVCS_renderpanel_t\fP * rp)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VCS from the source code\&.
