.TH "VCS_info" 3 "Version 0.0.1" "VCS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VCS_info
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <VCS_info\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsuccess\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBcharwidth\fP"
.br
.ti -1c
.RI "int \fBcharheight\fP"
.br
.ti -1c
.RI "SDL_Window * \fBwindow\fP"
.br
.ti -1c
.RI "SDL_Renderer * \fBrenderer\fP"
.br
.ti -1c
.RI "SDL_Texture * \fBrenderTexture\fP"
.br
.ti -1c
.RI "uint32_t * \fBfg\fP"
.br
.ti -1c
.RI "uint32_t * \fBbg\fP"
.br
.ti -1c
.RI "SDL_Surface * \fBtextSurface\fP"
.br
.ti -1c
.RI "TTF_Font * \fBfont\fP"
.br
.ti -1c
.RI "TTF_TextEngine * \fBtextEngine\fP"
.br
.ti -1c
.RI "VCS_renderpanel_t * \fBrp\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint32_t* bg"

.SS "int charheight"

.SS "int charwidth"

.SS "uint32_t* fg"

.SS "TTF_Font* font"

.SS "int height"

.SS "SDL_Renderer* renderer"

.SS "SDL_Texture* renderTexture"

.SS "VCS_renderpanel_t* rp"

.SS "int success"

.SS "TTF_TextEngine* textEngine"

.SS "SDL_Surface* textSurface"

.SS "int width"

.SS "SDL_Window* window"


.SH "Author"
.PP 
Generated automatically by Doxygen for VCS from the source code\&.
