.TH "VCS_dynchar" 3 "Version 0.0.1" "VCS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VCS_dynchar
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <VCS_dynchar\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBc\fP"
.br
.ti -1c
.RI "\fBVCS_cpushader\fP \fBfg\fP"
.br
.ti -1c
.RI "\fBVCS_cpushader\fP \fBbg\fP"
.br
.ti -1c
.RI "void * \fBfgarg\fP"
.br
.ti -1c
.RI "void * \fBbgarg\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBVCS_cpushader\fP bg"

.SS "void* bgarg"

.SS "char c"

.SS "\fBVCS_cpushader\fP fg"

.SS "void* fgarg"


.SH "Author"
.PP 
Generated automatically by Doxygen for VCS from the source code\&.
